### testando raiz do projeto
GET http://localhost:5186

### Listar todas as tarefas
GET http://localhost:5186/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5186/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "155ebd93-ca34-4897-9094-15c86aa0f2b0"
}

### Atualizar uma tarefa
PUT http://localhost:5186/tarefas/alterar/6a8b3e4d-5e4e-4f7e-bdc9-9181e456ad0e

### Listar tarefas concluídas
GET http://localhost:5186/tarefas/concluidas

### Listar tarefas nao concluidas
GET http://localhost:5186/tarefas/naoconcluidas

### Listar todas as categorias
GET http://localhost:5186/categoria/listar

### Cadastrar uma categoria
POST http://localhost:5186/categoria/cadastrar
Content-Type: application/json

{
    "nome": "Pessoal"
}